backend: webengine

content:
  canvas_reading: false
  headers:
    accept_language: qen-US,en;q=0.5
    #    user_agent: 'Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0'

downloads:
  location:
    suggestion: filename

fonts:
  default_size: '14px'

input:
  insert_mode:
    auto_load: true
    auto_enter: true
    auto_leave: true

session:
  lazy_restore: true

spellcheck:
  languages:
    - en-US

tabs:
  position: left
  select_on_remove: last-used
  title:
    format: '{index}: {current_title}'
    format_pinned: '{index}: {host}'
